version: 2.1
jobs:
  test:
    docker:
      - image: 'circleci/golang:latest'
    steps:
      - checkout
      - run:
          name: Reality Tests
          command: |
            go test ./...
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
            docker build -t bockyanggoh/auto-porter-go:latest .
            docker tag bockyanggoh/auto-porter-go:latest bockyanggoh/auto-porter-go:1.0.${CIRCLE_WORKFLOW_ID}